<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

## *Data Science Unit 4 Sprint 2*

# Sprint Challenge - Neural Network Foundations

Table of Problems

1. [Defining Neural Networks](#Q1)
2. [Chocolate Gummy Bears](#Q2)
    - Perceptron
    - Multilayer Perceptron
4. [Keras MMP](#Q3)

<a id="Q1"></a>
## 1. Define the following terms:

- **Neuron:**the main component of a neural network. takes in a value from the previous layer, performs a set computation on the value, and outputs a new value to the next layer.
- **Input Layer:**the first layer of a neural network where the information is fed in
- **Hidden Layer:**a group of neurons that take in a set of weighted inputs and produce an output through an activation function. every layer of neurons between the input layer and the output layer is a hidden layer.
- **Output Layer:**the final layer of a neural network which yields the output
- **Activation:** defines the output of a neuron for a given input.
- **Backpropagation:**the process used to train neural networks


## 2. Chocolate Gummy Bears <a id="Q2"></a>

Right now, you're probably thinking, "yuck, who the hell would eat that?". Great question. Your candy company wants to know too. And you thought I was kidding about the [Chocolate Gummy Bears](https://nuts.com/chocolatessweets/gummies/gummy-bears/milk-gummy-bears.html?utm_source=google&utm_medium=cpc&adpos=1o1&gclid=Cj0KCQjwrfvsBRD7ARIsAKuDvMOZrysDku3jGuWaDqf9TrV3x5JLXt1eqnVhN0KM6fMcbA1nod3h8AwaAvWwEALw_wcB). 

Let's assume that a candy company has gone out and collected information on the types of Halloween candy kids ate. Our candy company wants to predict the eating behavior of witches, warlocks, and ghosts -- aka costumed kids. They shared a sample dataset with us. Each row represents a piece of candy that a costumed child was presented with during "trick" or "treat". We know if the candy was `chocolate` (or not chocolate) or `gummy` (or not gummy). Your goal is to predict if the costumed kid `ate` the piece of candy. 

If both chocolate and gummy equal one, you've got a chocolate gummy bear on your hands!?!?!
![Chocolate Gummy Bear](https://ed910ae2d60f0d25bcb8-80550f96b5feb12604f4f720bfefb46d.ssl.cf1.rackcdn.com/3fb630c04435b7b5-2leZuM7_-zoom.jpg)

In [1]:
import pandas as pd
candy = pd.read_csv('chocolate_gummy_bears.csv')

In [2]:
candy.head()

chocolate  gummy  ate
0          0      1    1
1          1      0    1
2          0      1    1
3          0      0    0
4          1      1    0

### Perceptron

To make predictions on the `candy` dataframe. Build and train a Perceptron using numpy. Your target column is `ate` and your features: `chocolate` and `gummy`. Do not do any feature engineering. :P

Once you've trained your model, report your accuracy. You will not be able to achieve more than ~50% with the simple perceptron. Explain why you could not achieve a higher accuracy with the *simple perceptron* architecture, because it's possible to achieve ~95% accuracy on this dataset. Provide your answer in markdown (and *optional* data anlysis code) after your perceptron implementation. 

In [34]:
# Start your candy perceptron here
from sklearn.model_selection import train_test_split

X = candy[['chocolate', 'gummy']].values
y = candy['ate'].values

X_train, X_test = train_test_split(X, train_size=0.8, test_size=0.2)
X_train, X_val = train_test_split(X_train, train_size=0.8, test_size=0.2)
y_train, y_test = train_test_split(y, train_size=0.8, test_size=0.2)
y_train, y_val = train_test_split(y_train, train_size=0.8, test_size=0.2)

In [40]:
import numpy as np
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

class Perceptron:
  
  #constructor
  def __init__ (self):
    self.w = None
    self.b = None
    
  #model  
  def model(self, x):
    return 1 if (np.dot(self.w, x) >= self.b) else 0
  
  #predictor to predict on the data based on w
  def predict(self, X):
    Y = []
    for x in X:
      result = self.model(x)
      Y.append(result)
    return np.array(Y)
    
  def fit(self, X, Y, epochs = 1, lr = 1):
    self.w = np.ones(X.shape[1])
    self.b = 0
    accuracy = {}
    max_accuracy = 0
    wt_matrix = []
    #for all epochs
    for i in range(epochs):
      for x, y in zip(X, Y):
        y_pred = self.model(x)
        if y == 1 and y_pred == 0:
          self.w = self.w + lr * x
          self.b = self.b - lr * 1
        elif y == 0 and y_pred == 1:
          self.w = self.w - lr * x
          self.b = self.b + lr * 1
          
      wt_matrix.append(self.w)    
      accuracy[i] = accuracy_score(self.predict(X), Y)
      if (accuracy[i] > max_accuracy):
        max_accuracy = accuracy[i]
        chkptw = self.w
        chkptb = self.b
    #checkpoint (Save the weights and b value)
    self.w = chkptw
    self.b = chkptb
    
    #return the weight matrix, that contains weights over all epochs
    return np.array(wt_matrix)

model = Perceptron()
model.fit(X_train, y_train, 50, 0.1)
y_pred = model.predict(X_val)
print(accuracy_score(y_pred, y_val))

0.51125


In [ ]:
#this model probably needs a way to learn, like backpropogation

### Multilayer Perceptron <a id="Q3"></a>

Using the sample candy dataset, implement a Neural Network Multilayer Perceptron class that uses backpropagation to update the network's weights. Your Multilayer Perceptron should be implemented in Numpy. 
Your network must have one hidden layer.

Once you've trained your model, report your accuracy. Explain why your MLP's performance is considerably better than your simple perceptron's on the candy dataset. 

In [46]:
class NeuralNetwork:
    def __init__(self):
        # Set up Architecture of Neural Network
        self.input = 2
        self.hiddenNodes = 6 
        self.outputNodes = 1
        
        # Initial Weights
        self.weights1 = np.random.randn(self.input,self.hiddenNodes)
        self.weights2 = np.random.randn(self.hiddenNodes, self.outputNodes)
        

    def sigmoid(self, s):
        return 1 / (1+np.exp(-s))
    
    
    def sigmoidPrime(self, s):
        return s * (1 - s)
    
    
    def feed_forward(self,X):
        """
        Calculate the NN inference using feed forward.
        """
        
        # Weighted sum of inputs & hidden
        self.hidden_sum = np.dot(X, self.weights1)
        
        # Activations of weighted sum
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        
        # Weighted sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        
        # Final Activation of output
        self.activated_output = self.sigmoid(self.output_sum)
        
        return self.activated_output
    
    
    def backward(self, X, y, o):
        """
        Backward propagate through the network
        """
        self.o_error = y - o #error in output
        self.o_delta = self.o_error * self.sigmoidPrime(o) # apply derivative of sigmoid to error
        
        self.z2_error = self.o_delta.dot(self.weights2.T) # z2 error: how much our hidden layer weights were off
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.activated_hidden)
        
        self.weights1 += X.T.dot(self.z2_delta) #Adjust first set (input => hidden) weights
        self.weights2 += self.activated_hidden.T.dot(self.o_delta) #adjust second set (hidden => output) weights
        
        
    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X, y, o)

In [47]:
X = candy[['chocolate', 'gummy']].values
y = candy['ate'].values

X = X.astype('float64')
y = y.astype('float64')
y3 = np.reshape(y, (10000,1))
nn = NeuralNetwork()

print(X[0])
output = nn.feed_forward(X[0])
print("output", output)

[0. 1.]
output [0.60114423]


In [48]:
error = y3[0] - output
error

array([0.39885577])

In [49]:
output_all = nn.feed_forward(X)
error_all = y3 - output_all
print(output_all)
print(error_all)

[[0.60114423]
 [0.5364404 ]
 [0.60114423]
 ...
 [0.60114423]
 [0.60114423]
 [0.5364404 ]]
[[0.39885577]
 [0.4635596 ]
 [0.39885577]
 ...
 [0.39885577]
 [0.39885577]
 [0.4635596 ]]


P.S. Don't try candy gummy bears. They're disgusting. 

## 3. Keras MMP <a id="Q3"></a>

Implement a Multilayer Perceptron architecture of your choosing using the Keras library. Train your model and report its baseline accuracy. Then hyperparameter tune at least two parameters and report your model's accuracy.
Use the Heart Disease Dataset (binary classification)
Use an appropriate loss function for a binary classification task
Use an appropriate activation function on the final layer of your network.
Train your model using verbose output for ease of grading.
Use GridSearchCV or RandomSearchCV to hyperparameter tune your model. (for at least two hyperparameters)
When hyperparameter tuning, show you work by adding code cells for each new experiment.
Report the accuracy for each combination of hyperparameters as you test them so that we can easily see which resulted in the highest accuracy.
You must hyperparameter tune at least 3 parameters in order to get a 3 on this section.

In [42]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/heart.csv')
df = df.sample(frac=1)
print(df.shape)
df.head()

(303, 14)


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
290   61    1   0       148   203    0        1      161      0      0.0   
200   44    1   0       110   197    0        0      177      0      0.0   
40    51    0   2       140   308    0        0      142      0      1.5   
121   59    1   0       138   271    0        0      182      0      0.0   
136   60    0   2       120   178    1        1       96      0      0.0   

     slope  ca  thal  target  
290      2   1     3       0  
200      2   1     2       0  
40       2   1     2       1  
121      2   0     2       1  
136      2   0     2       1

In [43]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


X_train, X_test = train_test_split(df.drop(columns='target'), train_size=0.8, test_size=0.2)
y_train, y_test = train_test_split(df['target'], train_size=0.8, test_size=0.2)

scaler = StandardScaler()
scaler.fit_transform(X_train)
scaler.fit_transform(X_test)

model = Sequential()
model.add(Dense(13, input_dim=13, activation='sigmoid'))
model.add(Dense(8, activation='relu'))
model.add(Dense(4, activation='relu'))
model.add(Dense(2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

history = model.fit(X_train, y_train, epochs=50, verbose=True)
scores = model.evaluate(X_test, y_test)

Train on 242 samples
Epoch 1/50
242/242 [==============================] - 0s 2ms/sample - loss: 0.6932 - accuracy: 0.4959
Epoch 2/50
242/242 [==============================] - 0s 66us/sample - loss: 0.6929 - accuracy: 0.5372
Epoch 3/50
242/242 [==============================] - 0s 66us/sample - loss: 0.6927 - accuracy: 0.5372
Epoch 4/50
242/242 [==============================] - 0s 58us/sample - loss: 0.6924 - accuracy: 0.5413
Epoch 5/50
242/242 [==============================] - 0s 70us/sample - loss: 0.6922 - accuracy: 0.5413
Epoch 6/50
242/242 [==============================] - 0s 66us/sample - loss: 0.6919 - accuracy: 0.5413
Epoch 7/50
242/242 [==============================] - 0s 70us/sample - loss: 0.6919 - accuracy: 0.5413
Epoch 8/50
242/242 [==============================] - 0s 54us/sample - loss: 0.6917 - accuracy: 0.5372
Epoch 9/50
242/242 [==============================] - 0s 54us/sample - loss: 0.6915 - accuracy: 0.5413
Epoch 10/50
242/242 [==============================] 

In [44]:
from sklearn.model_selection import GridSearchCV
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier

def create_model():
    # create model
    model = Sequential()
    model.add(Dense(8, input_dim=13, activation='relu'))
    model.add(Dense(5, activation='relu'))
    model.add(Dense(1, activation='relu'))
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    
    return model

model = KerasClassifier(build_fn=create_model, verbose=0)
param_grid = {'batch_size': [60, 100],
              'epochs': [40, 100],
             }

grid = GridSearchCV(estimator = model, param_grid=param_grid, n_jobs=4)
grid_result = grid.fit(X_train, y_train)

In [45]:
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}")

Best: 0.49625850319862364 using {'batch_size': 60, 'epochs': 100}
Means: 0.49532312750816343, Stdev: 0.06973152048050725 with: {'batch_size': 60, 'epochs': 40}
Means: 0.49625850319862364, Stdev: 0.06916324811586916 with: {'batch_size': 60, 'epochs': 100}
Means: 0.49209184050559995, Stdev: 0.06315721096855095 with: {'batch_size': 100, 'epochs': 40}
Means: 0.4756802678108215, Stdev: 0.07806910510041724 with: {'batch_size': 100, 'epochs': 100}
